### ISSUE TITLE
What is the purpose of this assignment?

### ISSUE THREAD

**Issue by Bobby-Wan** [thukabjj/worker-pool-pattern#1]
Looking at the following piece of code, I can't understand why you are assigning to the variable twice in a row. Also, I don't get what can be in the stringPool before you Put something in it?

https://github.com/thukabjj/worker-pool-pattern/blob/71b76ef6ac719ce3db46388685cfaae5c347b367/golang-worker-pool/main.go#L155

**Comment by thukabjj** [comment]
Hi @Bobby-Wan, 
I hope you are fine. In advance, I would like to apologize for my late reply.

Answering your question, this is related to efficiently managing memory by utilizing `sync.Pool` to reuse string resources.
Basically, 
`entries := stringPool.Get().(string) ` is Retrieves a string from the pool.
`entries = string(chunk)`Converts the byte chunk to a string and assigns it to the

**Comment by Bobby-Wan** [comment]
Thank you. I looked into it after asking the question and it made sense after I did.
